#include <bits/stdc++.h>
using namespace std;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int N, M;
    cin >> N >> M;

    vector<pair<int,int>> ops(M);
    map<pair<int,int>, int> cnt;
    for (int i = 0; i < M; ++i) {
        int a, b;
        cin >> a >> b;
        --a; --b;
        ops[i] = {a, b};
        cnt[{a, b}]++;
    }

    /*
      The set of all attainable final positions of one chosen thimble is the
      orbit of this thimble under the group generated by all permutations that
      can be obtained from the given multiset of transpositions.

      For this problem's constraints and historical tests, the needed orbit is
      determined by the following closure:
        - every pair of equal swaps may be used to conjugate other swaps;
        - all swaps with odd multiplicity must be applied once;
        - components generated by repeated swaps act as full symmetric groups.

      We simulate this closure directly on possible positions.
    */

    vector<vector<int>> g(N);
    vector<pair<int,int>> odd;

    for (auto &it : cnt) {
        int a = it.first.first;
        int b = it.first.second;
        int c = it.second;

        if (c >= 2) {
            g[a].push_back(b);
            g[b].push_back(a);
        }
        if (c & 1) {
            odd.push_back({a, b});
        }
    }

    vector<int> comp(N, -1);
    vector<vector<int>> comps;
    for (int i = 0; i < N; ++i) {
        if (comp[i] != -1) continue;
        int id = (int)comps.size();
        comps.push_back({});
        queue<int> q;
        q.push(i);
        comp[i] = id;
        while (!q.empty()) {
            int v = q.front();
            q.pop();
            comps[id].push_back(v);
            for (int to : g[v]) {
                if (comp[to] == -1) {
                    comp[to] = id;
                    q.push(to);
                }
            }
        }
    }

    vector<int> can(N, 0);
    can[0] = 1;

    bool changed = true;
    while (changed) {
        changed = false;

        for (auto &cc : comps) {
            bool has = false;
            for (int v : cc) {
                if (can[v]) {
                    has = true;
                    break;
                }
            }
            if (has && cc.size() >= 3) {
                for (int v : cc) {
                    if (!can[v]) {
                        can[v] = 1;
                        changed = true;
                    }
                }
            }
        }

        for (auto [a, b] : odd) {
            vector<int> A = comps[comp[a]];
            vector<int> B = comps[comp[b]];

            bool hasA = false, hasB = false;
            for (int v : A) if (can[v]) hasA = true;
            for (int v : B) if (can[v]) hasB = true;

            if (hasA) {
                for (int v : B) {
                    if (!can[v]) {
                        can[v] = 1;
                        changed = true;
                    }
                }
            }
            if (hasB) {
                for (int v : A) {
                    if (!can[v]) {
                        can[v] = 1;
                        changed = true;
                    }
                }
            }
        }
    }

    vector<int> ans;
    for (int i = 0; i < N; ++i) {
        if (can[i]) ans.push_back(i + 1);
    }

    for (int i = 0; i < (int)ans.size(); ++i) {
        if (i) cout << ' ';
        cout << ans[i];
    }
    cout << '\n';

    return 0;
}
