#include<bits/stdc++.h>
using namespace std;
const double PI=acos(-1.0),EPS=1e-9;
double nA(double a){a=fmod(a,2*PI);if(a<0)a+=2*PI;return a;}
bool inCCW(double s,double e,double x){s=nA(s);e=nA(e);x=nA(x);if(e>=s-EPS)return x>=s-EPS&&x<=e+EPS;return x>=s-EPS||x<=e+EPS;}
struct Arc{double cx,cy,r,a1,a2,am;bool on(double a)const{a=nA(a);double s=nA(a1),e=nA(a2),m=nA(am);if(inCCW(s,e,m))return inCCW(s,e,a);return inCCW(e,s,a);}};
Arc makeArc(double x1,double y1,double x2,double y2,double xm,double ym){Arc arc;double ax=x1,ay=y1,bx=xm,by=ym,cx2=x2,cy2=y2;double D=2*(ax*(by-cy2)+bx*(cy2-ay)+cx2*(ay-by));double ux=((ax*ax+ay*ay)*(by-cy2)+(bx*bx+by*by)*(cy2-ay)+(cx2*cx2+cy2*cy2)*(ay-by))/D;double uy=((ax*ax+ay*ay)*(cx2-bx)+(bx*bx+by*by)*(ax-cx2)+(cx2*cx2+cy2*cy2)*(bx-ax))/D;arc.cx=ux;arc.cy=uy;arc.r=hypot(ax-ux,ay-uy);arc.a1=atan2(y1-uy,x1-ux);arc.a2=atan2(y2-uy,x2-ux);arc.am=atan2(ym-uy,xm-ux);return arc;}
int main(){int n;scanf("%d",&n);vector<Arc>arcs(n);for(int i=0;i<n;i++){double x1,y1,x2,y2,xm,ym;scanf("%lf%lf%lf%lf%lf%lf",&x1,&y1,&x2,&y2,&xm,&ym);arcs[i]=makeArc(x1,y1,x2,y2,xm,ym);}vector<pair<double,double>>pts;bool inf=false;for(int i=0;i<n&&!inf;i++)for(int j=i+1;j<n&&!inf;j++){Arc&A=arcs[i];Arc&B=arcs[j];double dx=B.cx-A.cx,dy=B.cy-A.cy;double d=hypot(dx,dy);if(d<EPS&&fabs(A.r-B.r)<EPS){// same circle
double a=nA(A.a1),b=nA(A.a2),m=nA(A.am);bool cw=!inCCW(a,b,m);// check overlap: sample points on A on B
double step=0.1;bool ov=false;for(double ang=0;ang<2*PI;ang+=step){double ta=ang;if(A.on(ta)){double px=A.cx+A.r*cos(ta),py=A.cy+A.r*sin(ta);double ba=atan2(py-B.cy,px-B.cx);if(B.on(ba)){ov=true;break;}}}if(ov)inf=true;}else{if(d>A.r+B.r+EPS||d<fabs(A.r-B.r)-EPS)continue;double a=(A.r*A.r-B.r*B.r+d*d)/(2*d);double h2=A.r*A.r-a*a;if(h2<0)h2=0;double h=sqrt(h2);double mx=A.cx+a*dx/d,my=A.cy+a*dy/d;double px1=mx+h*dy/d,py1=my-h*dx/d;double px2=mx-h*dy/d,py2=my+h*dx/d;auto addPt=[&](double px,double py){double a1=atan2(py-A.cy,px-A.cx);double a2=atan2(py-B.cy,px-B.cx);if(A.on(a1)&&B.on(a2)){for(auto&p:pts)if(hypot(p.first-px,p.second-py)<0.001)return;pts.push_back({px,py});}};addPt(px1,py1);if(h>EPS)addPt(px2,py2);}}if(inf){printf("Infinity\n");}else{sort(pts.begin(),pts.end(),[](auto&a,auto&b){if(fabs(a.first-b.first)>0.0001)return a.first<b.first;return a.second<b.second;});printf("%d\n",(int)pts.size());for(auto&p:pts)printf("%.3f %.3f\n",p.first,p.second);}}</pre>
