import sys
import random
from typing import List, Tuple

random.seed(20260612)  # deterministic hash base across runs

# We will implement a 61-bit mod rolling hash:
MOD = (1 << 61) - 1


def mod_add(a: int, b: int) -> int:
    """
    Modular addition under modulus 2^61-1 using the same trick
    as in the C++ code. This avoids overflow issues.
    """
    a += b + 1
    a = (a & MOD) + (a >> 61)
    return a - 1


def mod_sub(a: int, b: int) -> int:
    """
    Modular subtraction under modulus 2^61-1.
    Equivalent to a - b modulo MOD.
    """
    return mod_add(a, MOD - b)


def mod_mul(a: int, b: int) -> int:
    """
    Modular multiplication under modulus 2^61-1.
    We use 64-bit integer operations mimicking the C++ approach.
    Python supports big integers anyway, but we keep it consistent.
    """
    # Python has native big integers, so the C++ 64-bit splitting trick
    # (which relies on unsigned wrap-around) is unnecessary and was
    # ported incorrectly; plain modular multiplication is exact.
    return (a * b) % MOD


class Hasher:
    """
    Class to manage rolling hashes for a given base and MOD=2^61-1.
    """

    def __init__(self, max_len: int):
        # Random base in [1, MOD-1]; avoid 0 which would be useless
        self.base = random.randrange(1, MOD - 1)
        # Precompute base^i for i in [0, max_len]
        self.base_pow = [1] * (max_len + 1)
        for i in range(1, max_len + 1):
            self.base_pow[i] = mod_mul(self.base_pow[i - 1], self.base)

    def build(self, s: str) -> List[int]:
        """
        Build prefix hash array for string s.
        h[i] = hash of s[0..i] as a polynomial base representation.
        """
        h = [0] * len(s)
        for i, ch in enumerate(s):
            x = ord(ch)  # convert char to integer (same each run)
            if i == 0:
                h[i] = x % MOD
            else:
                h[i] = mod_add(mod_mul(h[i - 1], self.base), x)
        return h

    def hash_range(self, h: List[int], l: int, r: int) -> int:
        """
        Compute hash of substring s[l..r] using prefix hash array h[].
        We rely on them being generated by the same Hasher.
        """
        if l == 0:
            return h[r]
        length = r - l + 1
        return mod_sub(h[r], mod_mul(h[l - 1], self.base_pow[length]))


def check_len(len_sub: int,
              a: str, ha: List[int], a_rev: str, ha_rev: List[int],
              b: str, hb: List[int],
              hasher: Hasher) -> Tuple[int, int]:
    """
    For a given length len_sub, check if there exists a substring of 'a'
    of length len_sub that is a palindrome and also appears in 'b'.

    Returns (l, r) indices in 'a' if found, or (-1, -1) otherwise.
    """

    # Dictionary from hash -> (l,r) indices in a
    vis = {}

    n = len(a)
    # Enumerate substrings a[l..r] of length len_sub
    for i in range(len_sub - 1, n):
        l = i - len_sub + 1
        r = i

        # Corresponding positions in reversed a
        rev_l = n - 1 - r
        rev_r = n - 1 - l

        # Compute forward hash and reverse hash
        fh = hasher.hash_range(ha, l, r)
        rh = hasher.hash_range(ha_rev, rev_l, rev_r)

        # Check if a[l..r] is palindrome via hash equality
        if fh == rh:
            vis[fh] = (l, r)  # store or overwrite

    # Now scan substrings in 'b'
    m = len(b)
    for i in range(len_sub - 1, m):
        l = i - len_sub + 1
        r = i
        fh = hasher.hash_range(hb, l, r)
        if fh in vis:
            # We found a substring in b with the same hash as some palindrome in a
            return vis[fh]

    return -1, -1


def solve():
    data = sys.stdin.read().strip().split()
    if len(data) < 2:
        return
    a, b = data[0], data[1]

    n, m = len(a), len(b)
    max_len = n + m  # safe upper bound for powers

    # Initialize hasher with enough length
    hasher = Hasher(max_len)

    # Forward hash of a
    ha = hasher.build(a)
    # Forward hash of reversed a
    a_rev = a[::-1]
    ha_rev = hasher.build(a_rev)
    # Forward hash of b
    hb = hasher.build(b)

    best_l, best_r = -1, -1

    # Binary search odd palindrome lengths:
    # len = 2*mid - 1 for mid in [1..min(n,m)]
    lo, hi = 1, min(n, m)
    while lo <= hi:
        mid = (lo + hi) // 2
        length = 2 * mid - 1
        if length > min(n, m):  # sanity bound
            hi = mid - 1
            continue

        l, r = check_len(length, a, ha, a_rev, ha_rev, b, hb, hasher)
        if l != -1:
            # update best answer if longer
            if best_l == -1 or (r - l) > (best_r - best_l):
                best_l, best_r = l, r
            lo = mid + 1
        else:
            hi = mid - 1

    # Binary search even palindrome lengths:
    # len = 2*mid for mid in [1..min(n,m)]
    lo, hi = 1, min(n, m)
    while lo <= hi:
        mid = (lo + hi) // 2
        length = 2 * mid
        if length > min(n, m):
            hi = mid - 1
            continue

        l, r = check_len(length, a, ha, a_rev, ha_rev, b, hb, hasher)
        if l != -1:
            if best_l == -1 or (r - l) > (best_r - best_l):
                best_l, best_r = l, r
            lo = mid + 1
        else:
            hi = mid - 1

    # By problem constraints, there is at least one common character, so
    # some palindrome of length 1 must exist.
    assert best_l != -1

    # Output the resulting substring from a
    print(a[best_l:best_r + 1])


if __name__ == "__main__":
    solve()
