#include <iostream>
#include <vector>
#include <cctype>
#include <algorithm>
#include <cmath>

using namespace std;

int digitSum(int n) {
    int sum = 0;
    while (n > 0) {
        sum += n % 10;
        n /= 10;
    }
    return sum;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int N, K;
    cin >> N >> K;

    vector<int> indices(K);
    for (int i = 0; i < K; i++) {
        cin >> indices[i];
    }

    // We'll use a boolean vector to mark non-self-numbers
    // isSelf[i] = true means i is a self-number
    vector<bool> isSelf(N + 1, true);
    
    // Mark all numbers that are generated by some smaller number
    for (int i = 1; i <= N; i++) {
        int next = i + digitSum(i);
        if (next <= N) {
            isSelf[next] = false;
        }
    }

    // Collect all self-numbers up to N
    vector<int> selfNumbers;
    for (int i = 1; i <= N; i++) {
        if (isSelf[i]) {
            selfNumbers.push_back(i);
        }
    }

    // Output the count of self-numbers in [1..N]
    cout << selfNumbers.size() << "\n";

    // Output the requested self-numbers
    for (int i = 0; i < K; i++) {
        if (i > 0) cout << " ";
        cout << selfNumbers[indices[i] - 1];
    }
    cout << "\n";

    return 0;
}
